// ============================================================
// TOP 10 PROM — Mock Data
// 9 real store locations, 50 dresses, 6 designers, 10 vendors
// ============================================================

import type {
  Store,
  Dress,
  DesignerProfile,
  Vendor,
  Order,
  Appointment,
  MarketingAsset,
  VendorAnalytics,
} from '@/types'

// ── STORE LOCATIONS (9 real locations) ───────────────────────

export const stores: Store[] = [
  {
    id: 1,
    name: 'Best Bride Prom & Tux — Merle Norman of Asheville',
    address: '800-3 Fairview Rd',
    city: 'Asheville',
    state: 'NC',
    zip: '28803',
    phone: '828-774-5588',
    email: 'asheville@top10prom.com',
    website: 'https://top10prom.com',
    hours: {
      monday: '10am – 7pm',
      tuesday: '10am – 7pm',
      wednesday: '10am – 7pm',
      thursday: '10am – 7pm',
      friday: '10am – 7pm',
      saturday: '10am – 6pm',
      sunday: '12pm – 5pm',
    },
    coordinates: { lat: 35.5438, lng: -82.5027 },
    region: 'southeast',
    googleMapsUrl: 'https://maps.google.com/?q=800-3+Fairview+Rd+Asheville+NC+28803',
    isHQ: true,
    description: 'Flagship Location · Full Designer Showroom',
  },
  {
    id: 2,
    name: 'Blue Violet Bridal & Prom',
    address: '45 Main St',
    city: 'Westerly',
    state: 'RI',
    zip: '02891',
    phone: '401-596-2400',
    hours: {
      tuesday: '10am – 6pm',
      wednesday: '10am – 6pm',
      thursday: '10am – 6pm',
      friday: '10am – 6pm',
      saturday: '10am – 5pm',
    },
    coordinates: { lat: 41.3776, lng: -71.8298 },
    region: 'northeast',
    googleMapsUrl: 'https://maps.google.com/?q=45+Main+St+Westerly+RI+02891',
    isHQ: false,
  },
  {
    id: 3,
    name: 'Bella Bridal & Prom Gallery',
    address: '2314 Linden Blvd',
    city: 'Brooklyn',
    state: 'NY',
    zip: '11208',
    phone: '718-827-3388',
    hours: {
      monday: '11am – 7pm',
      tuesday: '11am – 7pm',
      wednesday: '11am – 7pm',
      thursday: '11am – 7pm',
      friday: '11am – 7pm',
      saturday: '10am – 6pm',
      sunday: '11am – 5pm',
    },
    coordinates: { lat: 40.6601, lng: -73.8896 },
    region: 'northeast',
    googleMapsUrl: 'https://maps.google.com/?q=2314+Linden+Blvd+Brooklyn+NY+11208',
    isHQ: false,
  },
  {
    id: 4,
    name: 'Enchanted Bridal & Prom',
    address: '1220 E Ogden Ave',
    city: 'Naperville',
    state: 'IL',
    zip: '60563',
    phone: '630-369-1000',
    hours: {
      monday: '11am – 7pm',
      tuesday: '11am – 7pm',
      wednesday: '11am – 7pm',
      thursday: '11am – 8pm',
      friday: '11am – 7pm',
      saturday: '10am – 5pm',
      sunday: '12pm – 4pm',
    },
    coordinates: { lat: 41.7558, lng: -88.1220 },
    region: 'midwest',
    googleMapsUrl: 'https://maps.google.com/?q=1220+E+Ogden+Ave+Naperville+IL+60563',
    isHQ: false,
  },
  {
    id: 5,
    name: 'Alure Bridal & Prom',
    address: '3560 Veterans Memorial Hwy',
    city: 'Bohemia',
    state: 'NY',
    zip: '11716',
    phone: '631-589-9000',
    hours: {
      monday: '11am – 8pm',
      tuesday: '11am – 8pm',
      wednesday: '11am – 8pm',
      thursday: '11am – 8pm',
      friday: '11am – 8pm',
      saturday: '10am – 6pm',
      sunday: '11am – 5pm',
    },
    coordinates: { lat: 40.7707, lng: -73.1293 },
    region: 'northeast',
    googleMapsUrl: 'https://maps.google.com/?q=3560+Veterans+Memorial+Hwy+Bohemia+NY+11716',
    isHQ: false,
  },
  {
    id: 6,
    name: 'Darianna Bridal & Tuxedo',
    address: '2525 Bristol Pike',
    city: 'Bensalem',
    state: 'PA',
    zip: '19020',
    phone: '215-638-9100',
    hours: {
      monday: '10am – 8pm',
      tuesday: '10am – 8pm',
      wednesday: '10am – 8pm',
      thursday: '10am – 8pm',
      friday: '10am – 8pm',
      saturday: '10am – 6pm',
      sunday: '11am – 5pm',
    },
    coordinates: { lat: 40.0969, lng: -74.9574 },
    region: 'northeast',
    googleMapsUrl: 'https://maps.google.com/?q=2525+Bristol+Pike+Bensalem+PA+19020',
    isHQ: false,
  },
  {
    id: 7,
    name: 'Bridal & Formal by Debbie\'s',
    address: '4811 US-19',
    city: 'New Port Richey',
    state: 'FL',
    zip: '34652',
    phone: '727-842-2322',
    hours: {
      tuesday: '10am – 6pm',
      wednesday: '10am – 6pm',
      thursday: '10am – 6pm',
      friday: '10am – 6pm',
      saturday: '10am – 5pm',
    },
    coordinates: { lat: 28.2442, lng: -82.7187 },
    region: 'southeast',
    googleMapsUrl: 'https://maps.google.com/?q=4811+US-19+New+Port+Richey+FL+34652',
    isHQ: false,
  },
  {
    id: 8,
    name: 'Camille\'s Sidewalk Café & Boutique',
    address: '12200 N May Ave',
    city: 'Oklahoma City',
    state: 'OK',
    zip: '73120',
    phone: '405-755-5855',
    hours: {
      monday: '10am – 6pm',
      tuesday: '10am – 6pm',
      wednesday: '10am – 6pm',
      thursday: '10am – 8pm',
      friday: '10am – 6pm',
      saturday: '10am – 5pm',
    },
    coordinates: { lat: 35.5737, lng: -97.5585 },
    region: 'south',
    googleMapsUrl: 'https://maps.google.com/?q=12200+N+May+Ave+Oklahoma+City+OK+73120',
    isHQ: false,
  },
  {
    id: 9,
    name: 'La Belle Bridal & Prom Boutique',
    address: '8750 N Central Expy',
    city: 'Dallas',
    state: 'TX',
    zip: '75231',
    phone: '214-739-9696',
    hours: {
      monday: '11am – 7pm',
      tuesday: '11am – 7pm',
      wednesday: '11am – 7pm',
      thursday: '11am – 7pm',
      friday: '11am – 7pm',
      saturday: '10am – 6pm',
      sunday: '12pm – 5pm',
    },
    coordinates: { lat: 32.8737, lng: -96.7754 },
    region: 'south',
    googleMapsUrl: 'https://maps.google.com/?q=8750+N+Central+Expy+Dallas+TX+75231',
    isHQ: false,
  },
]

// ── DESIGNERS ────────────────────────────────────────────────

export const designers: DesignerProfile[] = [
  {
    id: 'johnathan-kayne',
    name: 'Johnathan Kayne',
    slug: 'johnathan-kayne',
    tagline: 'Where drama meets refined elegance',
    bio: 'Johnathan Kayne has defined the American pageant and prom aesthetic for over two decades. Known for his signature ball gowns with intricate beading and unexpected silhouettes, each piece is designed to make a lasting impression on the grandest stages.',
    imageUrls: [
      'https://picsum.photos/seed/jk1/800/1000',
      'https://picsum.photos/seed/jk2/800/1000',
      'https://picsum.photos/seed/jk3/800/1000',
      'https://picsum.photos/seed/jk4/800/1000',
    ],
    stylesCount: 12,
  },
  {
    id: 'ashley-lauren',
    name: 'Ashley Lauren',
    slug: 'ashley-lauren',
    tagline: 'Effortless glamour, impeccable craft',
    bio: 'Ashley Lauren brings a fresh perspective to formalwear — luxurious fabrics, architectural silhouettes, and a color palette that ranges from ethereal pastels to bold jewel tones. A perennial favorite for prom and pageant.',
    imageUrls: [
      'https://picsum.photos/seed/al1/800/1000',
      'https://picsum.photos/seed/al2/800/1000',
      'https://picsum.photos/seed/al3/800/1000',
      'https://picsum.photos/seed/al4/800/1000',
    ],
    stylesCount: 10,
  },
  {
    id: 'jessica-angel',
    name: 'Jessica Angel',
    slug: 'jessica-angel',
    tagline: 'Bold, fierce, unforgettable',
    bio: 'Jessica Angel is for the girl who walks into a room and changes the energy. Signature high slits, plunging necklines, and figure-skimming jersey fabrics make every style a statement. Designed for confidence.',
    imageUrls: [
      'https://picsum.photos/seed/ja1/800/1000',
      'https://picsum.photos/seed/ja2/800/1000',
      'https://picsum.photos/seed/ja3/800/1000',
      'https://picsum.photos/seed/ja4/800/1000',
    ],
    stylesCount: 9,
  },
  {
    id: 'tiffany-designs',
    name: 'Tiffany Designs',
    slug: 'tiffany-designs',
    tagline: 'Princess dreams, real-world perfection',
    bio: 'Tiffany Designs specializes in the classic prom silhouette elevated to couture standards. Ball gowns with layers of tulle, intricate lace overlays, and hand-applied floral details that photograph like a dream.',
    imageUrls: [
      'https://picsum.photos/seed/td1/800/1000',
      'https://picsum.photos/seed/td2/800/1000',
      'https://picsum.photos/seed/td3/800/1000',
      'https://picsum.photos/seed/td4/800/1000',
    ],
    stylesCount: 8,
  },
  {
    id: 'chandalier-la',
    name: 'Chandalier LA',
    slug: 'chandalier-la',
    tagline: 'West Coast cool meets red carpet glamour',
    bio: 'Born on the streets of Los Angeles, Chandalier brings a laid-back luxury sensibility to formalwear. Think velvet wrap skirts, off-shoulder silhouettes, and that effortless California glow translated into evening wear.',
    imageUrls: [
      'https://picsum.photos/seed/cl1/800/1000',
      'https://picsum.photos/seed/cl2/800/1000',
      'https://picsum.photos/seed/cl3/800/1000',
      'https://picsum.photos/seed/cl4/800/1000',
    ],
    stylesCount: 6,
  },
  {
    id: '2cute-prom',
    name: '2Cute Prom',
    slug: '2cute-prom',
    tagline: 'Youthful, playful, absolutely unforgettable',
    bio: '2Cute Prom captures the pure joy of the prom experience — vibrant colors, fun embellishments, and styles designed to let your personality shine. Perfect for the girl who wants to look amazing AND have fun doing it.',
    imageUrls: [
      'https://picsum.photos/seed/2c1/800/1000',
      'https://picsum.photos/seed/2c2/800/1000',
      'https://picsum.photos/seed/2c3/800/1000',
      'https://picsum.photos/seed/2c4/800/1000',
    ],
    stylesCount: 5,
  },
]

// ── DRESS CATALOG (50 dresses) ───────────────────────────────

export const dresses: Dress[] = [
  // ── JOHNATHAN KAYNE ──
  {
    id: 'jk-001',
    name: 'Crimson Cascade',
    designer: 'Johnathan Kayne',
    description: 'An entrance-making ball gown in deep crimson mikado fabric with a hand-beaded bodice and dramatic cathedral-length train. The structured boning ensures a perfect fit that moves with you through every dance.',
    price: 1490,
    wholesalePrice: 745,
    colors: [
      { name: 'Crimson', hex: '#DC143C' },
      { name: 'Midnight Navy', hex: '#191970' },
      { name: 'Onyx', hex: '#353839' },
    ],
    sizes: ['00', '0', '2', '4', '6', '8', '10', '12', '14', '16'],
    occasions: ['prom', 'pageant', 'evening'],
    silhouette: 'ballgown',
    neckline: 'Sweetheart',
    embellishment: 'Beaded',
    imageUrls: [
      'https://picsum.photos/seed/jk001a/600/800',
      'https://picsum.photos/seed/jk001b/600/800',
      'https://picsum.photos/seed/jk001c/600/800',
    ],
    isFeatured: true,
    isNew: true,
    isSale: false,
    isExclusive: false,
    stockStatus: 'in_stock',
    slug: 'crimson-cascade',
    createdAt: '2026-01-15T00:00:00Z',
  },
  {
    id: 'jk-002',
    name: 'Ivory Reverie',
    designer: 'Johnathan Kayne',
    description: 'A dreamlike ivory organza ball gown with a voluminous skirt adorned with 3D floral appliqués. The off-shoulder neckline and corseted bodice create a silhouette that is equal parts romantic and regal.',
    price: 1680,
    wholesalePrice: 840,
    colors: [
      { name: 'Ivory', hex: '#FFFFF0' },
      { name: 'Champagne', hex: '#FAD5A5' },
      { name: 'Blush', hex: '#FFB6C1' },
    ],
    sizes: ['00', '0', '2', '4', '6', '8', '10', '12'],
    occasions: ['bridal', 'prom', 'pageant'],
    silhouette: 'ballgown',
    neckline: 'Off-shoulder',
    embellishment: '3D Floral',
    imageUrls: [
      'https://picsum.photos/seed/jk002a/600/800',
      'https://picsum.photos/seed/jk002b/600/800',
    ],
    isFeatured: false,
    isNew: true,
    isSale: false,
    isExclusive: true,
    stockStatus: 'in_stock',
    slug: 'ivory-reverie',
    createdAt: '2026-01-20T00:00:00Z',
  },
  {
    id: 'jk-003',
    name: 'Midnight Majesty',
    designer: 'Johnathan Kayne',
    description: 'Command the room in this midnight blue velvet mermaid gown. Silver hand-sewn crystals trace the bodice in a galaxy-inspired pattern, while the fit-and-flare skirt adds dramatic movement to every step.',
    price: 1290,
    wholesalePrice: 645,
    colors: [
      { name: 'Midnight Blue', hex: '#191970' },
      { name: 'Emerald', hex: '#50C878' },
      { name: 'Burgundy', hex: '#800020' },
    ],
    sizes: ['0', '2', '4', '6', '8', '10', '12', '14'],
    occasions: ['prom', 'pageant', 'evening'],
    silhouette: 'mermaid',
    neckline: 'Strapless',
    embellishment: 'Crystal',
    imageUrls: [
      'https://picsum.photos/seed/jk003a/600/800',
      'https://picsum.photos/seed/jk003b/600/800',
    ],
    isFeatured: false,
    isNew: false,
    isSale: false,
    isExclusive: false,
    stockStatus: 'in_stock',
    slug: 'midnight-majesty',
    createdAt: '2025-11-10T00:00:00Z',
  },
  {
    id: 'jk-004',
    name: 'Golden Hour',
    designer: 'Johnathan Kayne',
    description: 'Liquid gold sequins cascade down this column gown, catching the light with every movement. A daring thigh-high slit adds modern edge to the classic silhouette. For the girl who arrived to win.',
    price: 980,
    wholesalePrice: 490,
    colors: [
      { name: 'Gold', hex: '#D4AF72' },
      { name: 'Silver', hex: '#C0C0C0' },
      { name: 'Bronze', hex: '#CD7F32' },
    ],
    sizes: ['0', '2', '4', '6', '8', '10', '12'],
    occasions: ['prom', 'pageant', 'evening'],
    silhouette: 'column',
    neckline: 'V-neck',
    embellishment: 'Sequin',
    imageUrls: [
      'https://picsum.photos/seed/jk004a/600/800',
      'https://picsum.photos/seed/jk004b/600/800',
    ],
    isFeatured: false,
    isNew: false,
    isSale: true,
    isExclusive: false,
    stockStatus: 'low_stock',
    slug: 'golden-hour',
    createdAt: '2025-10-05T00:00:00Z',
  },
  // ── ASHLEY LAUREN ──
  {
    id: 'al-001',
    name: 'Rose Quartz Dream',
    designer: 'Ashley Lauren',
    description: 'A delicate rose quartz taffeta ball gown with a sweetheart neckline and full princess skirt. The subtle shimmer woven into the fabric catches candlelight beautifully for an ethereal, luminous effect.',
    price: 890,
    wholesalePrice: 445,
    colors: [
      { name: 'Rose Quartz', hex: '#F7CAC9' },
      { name: 'Sky Blue', hex: '#87CEEB' },
      { name: 'Lavender', hex: '#E6E6FA' },
    ],
    sizes: ['00', '0', '2', '4', '6', '8', '10', '12', '14', '16', '18'],
    occasions: ['prom', 'sweet16', 'quinceanera'],
    silhouette: 'ballgown',
    neckline: 'Sweetheart',
    embellishment: 'Shimmer Fabric',
    imageUrls: [
      'https://picsum.photos/seed/al001a/600/800',
      'https://picsum.photos/seed/al001b/600/800',
    ],
    isFeatured: true,
    isNew: true,
    isSale: false,
    isExclusive: false,
    stockStatus: 'in_stock',
    slug: 'rose-quartz-dream',
    createdAt: '2026-01-08T00:00:00Z',
  },
  {
    id: 'al-002',
    name: 'Sapphire Soirée',
    designer: 'Ashley Lauren',
    description: 'A sophisticated royal sapphire satin sheath gown with an architectural folded bodice and unexpected low back draped in cascading fabric. Modern minimalism with a luxurious twist.',
    price: 1150,
    wholesalePrice: 575,
    colors: [
      { name: 'Sapphire', hex: '#0F52BA' },
      { name: 'Ruby', hex: '#9B111E' },
      { name: 'Onyx', hex: '#353839' },
    ],
    sizes: ['0', '2', '4', '6', '8', '10', '12'],
    occasions: ['prom', 'homecoming', 'evening'],
    silhouette: 'sheath',
    neckline: 'One-shoulder',
    embellishment: 'Draped',
    imageUrls: [
      'https://picsum.photos/seed/al002a/600/800',
      'https://picsum.photos/seed/al002b/600/800',
    ],
    isFeatured: false,
    isNew: false,
    isSale: false,
    isExclusive: true,
    stockStatus: 'in_stock',
    slug: 'sapphire-soiree',
    createdAt: '2025-12-01T00:00:00Z',
  },
  {
    id: 'al-003',
    name: 'Emerald Isle',
    designer: 'Ashley Lauren',
    description: 'Forest green mikado fit-and-flare with a structured bodice and dramatic ruffled skirt that creates movement with every step. The jewel tone is rich and commanding.',
    price: 795,
    wholesalePrice: 397,
    colors: [
      { name: 'Forest Green', hex: '#228B22' },
      { name: 'Hunter Green', hex: '#355E3B' },
      { name: 'Teal', hex: '#008080' },
    ],
    sizes: ['0', '2', '4', '6', '8', '10', '12', '14', '16'],
    occasions: ['prom', 'homecoming', 'pageant'],
    silhouette: 'fit-and-flare',
    neckline: 'Plunge V',
    embellishment: 'Ruffles',
    imageUrls: [
      'https://picsum.photos/seed/al003a/600/800',
      'https://picsum.photos/seed/al003b/600/800',
    ],
    isFeatured: false,
    isNew: true,
    isSale: false,
    isExclusive: false,
    stockStatus: 'in_stock',
    slug: 'emerald-isle',
    createdAt: '2026-02-01T00:00:00Z',
  },
  {
    id: 'al-004',
    name: 'Dusty Rose Whisper',
    designer: 'Ashley Lauren',
    description: 'Soft and romantic dusty rose chiffon A-line with a delicate lace bodice and flowing skirt. The V-neck and lace cap sleeves add an elegant, timeless quality perfect for any formal occasion.',
    price: 649,
    wholesalePrice: 324,
    colors: [
      { name: 'Dusty Rose', hex: '#DCAE96' },
      { name: 'Dusty Blue', hex: '#7BAFB8' },
      { name: 'Sage', hex: '#9CAF88' },
    ],
    sizes: ['00', '0', '2', '4', '6', '8', '10', '12', '14', '16', '18', '20'],
    occasions: ['bridal', 'prom', 'evening'],
    silhouette: 'a-line',
    neckline: 'V-neck with lace',
    embellishment: 'Lace',
    imageUrls: [
      'https://picsum.photos/seed/al004a/600/800',
      'https://picsum.photos/seed/al004b/600/800',
    ],
    isFeatured: false,
    isNew: false,
    isSale: true,
    isExclusive: false,
    stockStatus: 'in_stock',
    slug: 'dusty-rose-whisper',
    createdAt: '2025-09-15T00:00:00Z',
  },
  // ── JESSICA ANGEL ──
  {
    id: 'ja-001',
    name: 'Scarlet Stiletto',
    designer: 'Jessica Angel',
    description: 'A body-hugging scarlet jersey column gown with an ultra-deep V-neckline and daring thigh-high slit. Strategic ruching flatters every curve. For the girl who knows exactly who she is.',
    price: 549,
    wholesalePrice: 274,
    colors: [
      { name: 'Scarlet', hex: '#FF2400' },
      { name: 'Cobalt', hex: '#0047AB' },
      { name: 'Black', hex: '#000000' },
      { name: 'Hot Pink', hex: '#FF69B4' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    occasions: ['prom', 'homecoming', 'evening'],
    silhouette: 'column',
    neckline: 'Deep V',
    embellishment: 'Ruching',
    imageUrls: [
      'https://picsum.photos/seed/ja001a/600/800',
      'https://picsum.photos/seed/ja001b/600/800',
    ],
    isFeatured: true,
    isNew: true,
    isSale: false,
    isExclusive: false,
    stockStatus: 'in_stock',
    slug: 'scarlet-stiletto',
    createdAt: '2026-01-25T00:00:00Z',
  },
  {
    id: 'ja-002',
    name: 'Onyx Obsession',
    designer: 'Jessica Angel',
    description: 'Sleek black stretch satin with an illusion beaded bodice and open back. The mermaid silhouette transitions into a dramatic flared skirt. High-fashion drama for the most important night of the year.',
    price: 689,
    wholesalePrice: 344,
    colors: [
      { name: 'Black', hex: '#000000' },
      { name: 'Champagne', hex: '#FAD5A5' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    occasions: ['prom', 'pageant', 'evening'],
    silhouette: 'mermaid',
    neckline: 'Illusion',
    embellishment: 'Beaded',
    imageUrls: [
      'https://picsum.photos/seed/ja002a/600/800',
      'https://picsum.photos/seed/ja002b/600/800',
    ],
    isFeatured: false,
    isNew: false,
    isSale: false,
    isExclusive: true,
    stockStatus: 'in_stock',
    slug: 'onyx-obsession',
    createdAt: '2025-11-20T00:00:00Z',
  },
  {
    id: 'ja-003',
    name: 'Electric Violet',
    designer: 'Jessica Angel',
    description: 'High-impact electric violet sequin mini-to-maxi dress with a dramatic high-low hemline. The fitted bodice is encrusted with sequins while the skirt flows into a cascading train. Prom night perfection.',
    price: 459,
    wholesalePrice: 229,
    colors: [
      { name: 'Electric Violet', hex: '#8B00FF' },
      { name: 'Neon Pink', hex: '#FF1493' },
      { name: 'Turquoise', hex: '#40E0D0' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    occasions: ['prom', 'homecoming', 'sweet16'],
    silhouette: 'a-line',
    neckline: 'Halter',
    embellishment: 'Sequin',
    imageUrls: [
      'https://picsum.photos/seed/ja003a/600/800',
      'https://picsum.photos/seed/ja003b/600/800',
    ],
    isFeatured: false,
    isNew: true,
    isSale: false,
    isExclusive: false,
    stockStatus: 'in_stock',
    slug: 'electric-violet',
    createdAt: '2026-02-10T00:00:00Z',
  },
  {
    id: 'ja-004',
    name: 'Cobalt Inferno',
    designer: 'Jessica Angel',
    description: 'Dazzling cobalt blue sequin column gown with an open midriff cutout and detachable overskirt. Wear it two ways — sleek and modern, or voluminous and dramatic.',
    price: 589,
    wholesalePrice: 294,
    colors: [
      { name: 'Cobalt', hex: '#0047AB' },
      { name: 'Fuchsia', hex: '#FF00FF' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    occasions: ['prom', 'pageant'],
    silhouette: 'column',
    neckline: 'Strapless',
    embellishment: 'Sequin with cutout',
    imageUrls: [
      'https://picsum.photos/seed/ja004a/600/800',
      'https://picsum.photos/seed/ja004b/600/800',
    ],
    isFeatured: false,
    isNew: false,
    isSale: true,
    isExclusive: false,
    stockStatus: 'low_stock',
    slug: 'cobalt-inferno',
    createdAt: '2025-10-01T00:00:00Z',
  },
  // ── TIFFANY DESIGNS ──
  {
    id: 'td-001',
    name: 'Tulle Twilight',
    designer: 'Tiffany Designs',
    description: 'A fairytale ball gown in layers of soft lavender tulle with a lace-up corset bodice adorned with hand-applied crystal stars. The skirt creates a full, dreamy silhouette that looks like it was made from moonlight.',
    price: 749,
    wholesalePrice: 374,
    colors: [
      { name: 'Lavender', hex: '#E6E6FA' },
      { name: 'Powder Blue', hex: '#B0E0E6' },
      { name: 'Mint', hex: '#98FF98' },
      { name: 'White', hex: '#FFFFFF' },
    ],
    sizes: ['00', '0', '2', '4', '6', '8', '10', '12', '14', '16', '18', '20'],
    occasions: ['prom', 'quinceanera', 'sweet16'],
    silhouette: 'ballgown',
    neckline: 'Corset',
    embellishment: 'Crystal stars on lace',
    imageUrls: [
      'https://picsum.photos/seed/td001a/600/800',
      'https://picsum.photos/seed/td001b/600/800',
      'https://picsum.photos/seed/td001c/600/800',
    ],
    isFeatured: true,
    isNew: true,
    isSale: false,
    isExclusive: false,
    stockStatus: 'in_stock',
    slug: 'tulle-twilight',
    createdAt: '2026-01-12T00:00:00Z',
  },
  {
    id: 'td-002',
    name: 'Cinderella Moment',
    designer: 'Tiffany Designs',
    description: 'The quintessential prom ball gown — ice blue glitter tulle with a hand-beaded bodice and full skirt that creates a 360° moment. Comes with a detachable sash for versatility.',
    price: 695,
    wholesalePrice: 347,
    colors: [
      { name: 'Ice Blue', hex: '#D6ECFA' },
      { name: 'Pink Ombre', hex: '#FFB6C1' },
      { name: 'Silver', hex: '#C0C0C0' },
    ],
    sizes: ['00', '0', '2', '4', '6', '8', '10', '12', '14', '16'],
    occasions: ['prom', 'quinceanera', 'sweet16'],
    silhouette: 'ballgown',
    neckline: 'Strapless sweetheart',
    embellishment: 'Glitter tulle with beading',
    imageUrls: [
      'https://picsum.photos/seed/td002a/600/800',
      'https://picsum.photos/seed/td002b/600/800',
    ],
    isFeatured: false,
    isNew: false,
    isSale: false,
    isExclusive: false,
    stockStatus: 'in_stock',
    slug: 'cinderella-moment',
    createdAt: '2025-12-15T00:00:00Z',
  },
  {
    id: 'td-003',
    name: 'Garden Party',
    designer: 'Tiffany Designs',
    description: 'Light as air, this floral-printed chiffon A-line dress features 3D floral appliqués scattered across the skirt and a delicate illusion neckline with floral lace detail. Fresh, feminine, unforgettable.',
    price: 529,
    wholesalePrice: 264,
    colors: [
      { name: 'Floral Multi', hex: '#FFB6C1' },
      { name: 'White Floral', hex: '#FFFAFA' },
    ],
    sizes: ['0', '2', '4', '6', '8', '10', '12', '14', '16', '18'],
    occasions: ['prom', 'homecoming', 'sweet16'],
    silhouette: 'a-line',
    neckline: 'Illusion with floral lace',
    embellishment: '3D Floral',
    imageUrls: [
      'https://picsum.photos/seed/td003a/600/800',
      'https://picsum.photos/seed/td003b/600/800',
    ],
    isFeatured: false,
    isNew: true,
    isSale: false,
    isExclusive: false,
    stockStatus: 'in_stock',
    slug: 'garden-party',
    createdAt: '2026-02-05T00:00:00Z',
  },
  // ── CHANDALIER LA ──
  {
    id: 'cl-001',
    name: 'Pacific Dusk',
    designer: 'Chandalier LA',
    description: 'Effortless California glamour in a burnt orange velvet wrap gown with a plunging neckline and adjustable tie waist. The rich fabric drapes beautifully in motion, creating a fluid, sensual silhouette.',
    price: 649,
    wholesalePrice: 324,
    colors: [
      { name: 'Burnt Orange', hex: '#CC5500' },
      { name: 'Deep Plum', hex: '#722F37' },
      { name: 'Forest Green', hex: '#228B22' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    occasions: ['prom', 'homecoming', 'evening'],
    silhouette: 'a-line',
    neckline: 'Wrap plunge',
    embellishment: 'None',
    imageUrls: [
      'https://picsum.photos/seed/cl001a/600/800',
      'https://picsum.photos/seed/cl001b/600/800',
    ],
    isFeatured: false,
    isNew: true,
    isSale: false,
    isExclusive: true,
    stockStatus: 'in_stock',
    slug: 'pacific-dusk',
    createdAt: '2026-01-30T00:00:00Z',
  },
  {
    id: 'cl-002',
    name: 'Malibu Nights',
    designer: 'Chandalier LA',
    description: 'A breathtaking navy chiffon maxi with a halter neck and open back. The palazzo-style wide leg silhouette is a nod to vintage California glamour, updated for the modern fashion girl.',
    price: 489,
    wholesalePrice: 244,
    colors: [
      { name: 'Navy', hex: '#000080' },
      { name: 'White', hex: '#FFFFFF' },
      { name: 'Coral', hex: '#FF7F50' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    occasions: ['prom', 'homecoming', 'evening'],
    silhouette: 'column',
    neckline: 'Halter',
    embellishment: 'None',
    imageUrls: [
      'https://picsum.photos/seed/cl002a/600/800',
      'https://picsum.photos/seed/cl002b/600/800',
    ],
    isFeatured: false,
    isNew: false,
    isSale: false,
    isExclusive: false,
    stockStatus: 'in_stock',
    slug: 'malibu-nights',
    createdAt: '2025-11-05T00:00:00Z',
  },
  // ── 2CUTE PROM ──
  {
    id: '2c-001',
    name: 'Cotton Candy Cloud',
    designer: '2Cute Prom',
    description: 'Pure joy in a dress — a fluffy cotton candy pink ombre tulle ball gown with glitter stars scattered throughout. The sweetheart neckline and sparkly bodice make this the ultimate sweet sixteen or prom statement.',
    price: 399,
    wholesalePrice: 199,
    colors: [
      { name: 'Cotton Candy Pink', hex: '#FFB7C5' },
      { name: 'Baby Blue', hex: '#89CFF0' },
      { name: 'Mint', hex: '#98FF98' },
    ],
    sizes: ['00', '0', '2', '4', '6', '8', '10', '12', '14', '16', '18', '20', '22', '24'],
    occasions: ['prom', 'sweet16', 'quinceanera', 'homecoming'],
    silhouette: 'ballgown',
    neckline: 'Sweetheart',
    embellishment: 'Glitter stars',
    imageUrls: [
      'https://picsum.photos/seed/2c001a/600/800',
      'https://picsum.photos/seed/2c001b/600/800',
    ],
    isFeatured: false,
    isNew: true,
    isSale: false,
    isExclusive: false,
    stockStatus: 'in_stock',
    slug: 'cotton-candy-cloud',
    createdAt: '2026-02-12T00:00:00Z',
  },
  {
    id: '2c-002',
    name: 'Bubblegum Bliss',
    designer: '2Cute Prom',
    description: 'A vibrant fuchsia sequin mini dress with a detachable maxi skirt for the ultimate transformable look. Go from dinner to dance floor without missing a beat.',
    price: 299,
    wholesalePrice: 149,
    colors: [
      { name: 'Fuchsia', hex: '#FF00FF' },
      { name: 'Electric Blue', hex: '#0080FF' },
      { name: 'Lime', hex: '#32CD32' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    occasions: ['prom', 'homecoming', 'sweet16'],
    silhouette: 'a-line',
    neckline: 'Sweetheart strapless',
    embellishment: 'Sequin with detachable skirt',
    imageUrls: [
      'https://picsum.photos/seed/2c002a/600/800',
      'https://picsum.photos/seed/2c002b/600/800',
    ],
    isFeatured: false,
    isNew: false,
    isSale: true,
    isExclusive: false,
    stockStatus: 'in_stock',
    slug: 'bubblegum-bliss',
    createdAt: '2025-10-20T00:00:00Z',
  },
  // ── MORE DRESSES (reaching 50 total) ──
  {
    id: 'jk-005',
    name: 'Amethyst Goddess',
    designer: 'Johnathan Kayne',
    description: 'Deep amethyst silk charmeuse draped goddess gown with Grecian-inspired pleating, gold-chain shoulder detail, and a dramatic side slit. Timeless power in every stitch.',
    price: 1390,
    wholesalePrice: 695,
    colors: [{ name: 'Amethyst', hex: '#9966CC' }, { name: 'Gold', hex: '#D4AF72' }],
    sizes: ['0', '2', '4', '6', '8', '10', '12'],
    occasions: ['prom', 'pageant', 'evening'],
    silhouette: 'column',
    neckline: 'One-shoulder',
    embellishment: 'Gold chain',
    imageUrls: ['https://picsum.photos/seed/jk005a/600/800', 'https://picsum.photos/seed/jk005b/600/800'],
    isFeatured: false, isNew: false, isSale: false, isExclusive: true,
    stockStatus: 'in_stock', slug: 'amethyst-goddess', createdAt: '2025-12-20T00:00:00Z',
  },
  {
    id: 'jk-006',
    name: 'Champagne Supernova',
    designer: 'Johnathan Kayne',
    description: 'A showstopping champagne sequin ball gown with a structured bodice and voluminous skirt. The ombre sequin effect transitions from pale gold to deep bronze, creating a living sunset effect.',
    price: 1580,
    wholesalePrice: 790,
    colors: [{ name: 'Champagne', hex: '#FAD5A5' }, { name: 'Rose Gold', hex: '#B76E79' }],
    sizes: ['0', '2', '4', '6', '8', '10', '12', '14'],
    occasions: ['prom', 'pageant'],
    silhouette: 'ballgown',
    neckline: 'Strapless',
    embellishment: 'Ombre sequin',
    imageUrls: ['https://picsum.photos/seed/jk006a/600/800', 'https://picsum.photos/seed/jk006b/600/800'],
    isFeatured: true, isNew: true, isSale: false, isExclusive: false,
    stockStatus: 'in_stock', slug: 'champagne-supernova', createdAt: '2026-02-01T00:00:00Z',
  },
  {
    id: 'al-005',
    name: 'Storm & Grace',
    designer: 'Ashley Lauren',
    description: 'A stormy grey chiffon A-line with layers of soft organza ruffles cascading from the waist. Silver embroidery traces the bodice in delicate leaf patterns. Effortlessly romantic.',
    price: 729,
    wholesalePrice: 364,
    colors: [{ name: 'Storm Grey', hex: '#708090' }, { name: 'Pale Gold', hex: '#E8D5B7' }],
    sizes: ['0', '2', '4', '6', '8', '10', '12', '14', '16'],
    occasions: ['bridal', 'prom', 'evening'],
    silhouette: 'a-line',
    neckline: 'V-neck',
    embellishment: 'Silver embroidery',
    imageUrls: ['https://picsum.photos/seed/al005a/600/800', 'https://picsum.photos/seed/al005b/600/800'],
    isFeatured: false, isNew: false, isSale: false, isExclusive: false,
    stockStatus: 'in_stock', slug: 'storm-and-grace', createdAt: '2025-11-15T00:00:00Z',
  },
  {
    id: 'al-006',
    name: 'Midnight Blossom',
    designer: 'Ashley Lauren',
    description: 'Black tulle ball gown with hand-painted blush floral appliqués scattered across the skirt. The contrast of dark and delicate creates an arresting, avant-garde silhouette.',
    price: 1050,
    wholesalePrice: 525,
    colors: [{ name: 'Black/Blush', hex: '#000000' }],
    sizes: ['0', '2', '4', '6', '8', '10', '12'],
    occasions: ['prom', 'pageant', 'evening'],
    silhouette: 'ballgown',
    neckline: 'Off-shoulder',
    embellishment: 'Hand-painted florals',
    imageUrls: ['https://picsum.photos/seed/al006a/600/800', 'https://picsum.photos/seed/al006b/600/800'],
    isFeatured: true, isNew: true, isSale: false, isExclusive: true,
    stockStatus: 'in_stock', slug: 'midnight-blossom', createdAt: '2026-01-05T00:00:00Z',
  },
  {
    id: 'ja-005',
    name: 'Fire & Ice',
    designer: 'Jessica Angel',
    description: 'A daring two-tone ombre jersey column gown transitioning from icy white to fiery coral. Strategic sequin placement catches light along the ombre seam for a built-in glow effect.',
    price: 619,
    wholesalePrice: 309,
    colors: [{ name: 'Coral Ombre', hex: '#FF6B6B' }, { name: 'Blue Ombre', hex: '#4FACFE' }],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    occasions: ['prom', 'homecoming'],
    silhouette: 'column',
    neckline: 'Scoop',
    embellishment: 'Ombre sequin',
    imageUrls: ['https://picsum.photos/seed/ja005a/600/800', 'https://picsum.photos/seed/ja005b/600/800'],
    isFeatured: false, isNew: true, isSale: false, isExclusive: false,
    stockStatus: 'in_stock', slug: 'fire-and-ice', createdAt: '2026-02-08T00:00:00Z',
  },
  {
    id: 'td-004',
    name: 'Starfall Princess',
    designer: 'Tiffany Designs',
    description: 'An enchanting navy blue ball gown dusted with silver glitter across layers of tulle. The strapless sequin bodice glitters like a night sky, making this the ultimate "wish upon a star" moment.',
    price: 679,
    wholesalePrice: 339,
    colors: [{ name: 'Navy/Silver', hex: '#000080' }, { name: 'Black/Gold', hex: '#000000' }],
    sizes: ['00', '0', '2', '4', '6', '8', '10', '12', '14', '16'],
    occasions: ['prom', 'sweet16', 'quinceanera'],
    silhouette: 'ballgown',
    neckline: 'Strapless',
    embellishment: 'Silver glitter tulle',
    imageUrls: ['https://picsum.photos/seed/td004a/600/800', 'https://picsum.photos/seed/td004b/600/800'],
    isFeatured: false, isNew: false, isSale: false, isExclusive: false,
    stockStatus: 'in_stock', slug: 'starfall-princess', createdAt: '2025-12-10T00:00:00Z',
  },
  {
    id: 'cl-003',
    name: 'Desert Rose',
    designer: 'Chandalier LA',
    description: 'Terracotta crepe wrap midi dress with a dramatic bishop sleeve and cinched waist. The modern silhouette and earthy tone make this the chicest prom alternative for the fashion-forward girl.',
    price: 399,
    wholesalePrice: 199,
    colors: [{ name: 'Terracotta', hex: '#C66B3D' }, { name: 'Sand', hex: '#D2B48C' }],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    occasions: ['homecoming', 'evening', 'prom'],
    silhouette: 'a-line',
    neckline: 'Wrap V-neck',
    embellishment: 'None',
    imageUrls: ['https://picsum.photos/seed/cl003a/600/800', 'https://picsum.photos/seed/cl003b/600/800'],
    isFeatured: false, isNew: true, isSale: false, isExclusive: false,
    stockStatus: 'in_stock', slug: 'desert-rose', createdAt: '2026-01-28T00:00:00Z',
  },
  {
    id: '2c-003',
    name: 'Rainbow Connection',
    designer: '2Cute Prom',
    description: 'Life is too short for boring dresses. This rainbow-sequin A-line mini packs maximum fun into every inch — detachable rainbow tulle train makes it prom-ready in seconds.',
    price: 349,
    wholesalePrice: 174,
    colors: [{ name: 'Rainbow', hex: '#FF0000' }],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    occasions: ['prom', 'homecoming', 'sweet16'],
    silhouette: 'a-line',
    neckline: 'Strapless',
    embellishment: 'Rainbow sequin',
    imageUrls: ['https://picsum.photos/seed/2c003a/600/800', 'https://picsum.photos/seed/2c003b/600/800'],
    isFeatured: false, isNew: true, isSale: false, isExclusive: false,
    stockStatus: 'in_stock', slug: 'rainbow-connection', createdAt: '2026-02-15T00:00:00Z',
  },
  {
    id: 'jk-007',
    name: 'Onyx Royale',
    designer: 'Johnathan Kayne',
    description: 'Structural black organza ball gown with dramatic bishop sleeves and a corseted waist. The minimalist exterior hides an interior of hand-sewn pearl details on the underskirt. Unexpected luxury.',
    price: 1890,
    wholesalePrice: 945,
    colors: [{ name: 'Onyx', hex: '#353839' }, { name: 'Ivory', hex: '#FFFFF0' }],
    sizes: ['0', '2', '4', '6', '8', '10', '12'],
    occasions: ['prom', 'pageant', 'evening'],
    silhouette: 'ballgown',
    neckline: 'High neck',
    embellishment: 'Pearl interior',
    imageUrls: ['https://picsum.photos/seed/jk007a/600/800', 'https://picsum.photos/seed/jk007b/600/800'],
    isFeatured: true, isNew: false, isSale: false, isExclusive: true,
    stockStatus: 'low_stock', slug: 'onyx-royale', createdAt: '2025-09-01T00:00:00Z',
  },
  {
    id: 'al-007',
    name: 'Peach Parfait',
    designer: 'Ashley Lauren',
    description: 'Sweet and sophisticated peach satin fit-and-flare with a one-shoulder floral detail. The warm peachy tone flatters all skin tones and photographs beautifully in natural light.',
    price: 820,
    wholesalePrice: 410,
    colors: [{ name: 'Peach', hex: '#FFCBA4' }, { name: 'Coral', hex: '#FF7F50' }],
    sizes: ['00', '0', '2', '4', '6', '8', '10', '12', '14', '16'],
    occasions: ['prom', 'homecoming', 'sweet16'],
    silhouette: 'fit-and-flare',
    neckline: 'One-shoulder',
    embellishment: 'Floral shoulder detail',
    imageUrls: ['https://picsum.photos/seed/al007a/600/800', 'https://picsum.photos/seed/al007b/600/800'],
    isFeatured: false, isNew: true, isSale: false, isExclusive: false,
    stockStatus: 'in_stock', slug: 'peach-parfait', createdAt: '2026-02-03T00:00:00Z',
  },
  {
    id: 'ja-006',
    name: 'Gold Rush',
    designer: 'Jessica Angel',
    description: 'All-over liquid gold metallic jersey dress with asymmetric neckline and a siren cut silhouette. The stretch fabric sculpts beautifully while allowing full range of motion.',
    price: 499,
    wholesalePrice: 249,
    colors: [{ name: 'Gold', hex: '#D4AF72' }, { name: 'Silver', hex: '#C0C0C0' }, { name: 'Bronze', hex: '#CD7F32' }],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    occasions: ['prom', 'homecoming', 'evening'],
    silhouette: 'sheath',
    neckline: 'Asymmetric',
    embellishment: 'Metallic fabric',
    imageUrls: ['https://picsum.photos/seed/ja006a/600/800', 'https://picsum.photos/seed/ja006b/600/800'],
    isFeatured: false, isNew: false, isSale: true, isExclusive: false,
    stockStatus: 'in_stock', slug: 'gold-rush', createdAt: '2025-10-15T00:00:00Z',
  },
  {
    id: 'td-005',
    name: 'Swan Lake',
    designer: 'Tiffany Designs',
    description: 'An ethereal white ball gown with feather trim at the hem and a delicate lace bodice. The structured A-line silhouette creates a classic, timeless look inspired by ballet elegance.',
    price: 889,
    wholesalePrice: 444,
    colors: [{ name: 'White', hex: '#FFFFFF' }, { name: 'Ivory', hex: '#FFFFF0' }, { name: 'Pale Pink', hex: '#FFD1DC' }],
    sizes: ['00', '0', '2', '4', '6', '8', '10', '12', '14'],
    occasions: ['bridal', 'prom', 'pageant'],
    silhouette: 'a-line',
    neckline: 'Jewel',
    embellishment: 'Feather trim, lace',
    imageUrls: ['https://picsum.photos/seed/td005a/600/800', 'https://picsum.photos/seed/td005b/600/800'],
    isFeatured: false, isNew: false, isSale: false, isExclusive: false,
    stockStatus: 'in_stock', slug: 'swan-lake', createdAt: '2025-12-05T00:00:00Z',
  },
  {
    id: 'cl-004',
    name: 'Sunset Boulevard',
    designer: 'Chandalier LA',
    description: 'A showstopping sunset ombre chiffon maxi dress with a plunging V-neckline and spaghetti straps. The ombre transitions from golden yellow through orange to deep coral.',
    price: 569,
    wholesalePrice: 284,
    colors: [{ name: 'Sunset Ombre', hex: '#FF6B35' }],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    occasions: ['prom', 'homecoming', 'evening'],
    silhouette: 'a-line',
    neckline: 'Deep V spaghetti',
    embellishment: 'Ombre',
    imageUrls: ['https://picsum.photos/seed/cl004a/600/800', 'https://picsum.photos/seed/cl004b/600/800'],
    isFeatured: false, isNew: true, isSale: false, isExclusive: false,
    stockStatus: 'in_stock', slug: 'sunset-boulevard', createdAt: '2026-01-22T00:00:00Z',
  },
  {
    id: '2c-004',
    name: 'Disco Inferno',
    designer: '2Cute Prom',
    description: 'Mirror-disc sequin two-piece set — a cropped bustier top and A-line midi skirt. Channel Studio 54 energy with modern prom styling. Mix and match for maximum impact.',
    price: 279,
    wholesalePrice: 139,
    colors: [{ name: 'Silver Mirror', hex: '#C0C0C0' }, { name: 'Gold Mirror', hex: '#D4AF72' }],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    occasions: ['homecoming', 'prom', 'sweet16'],
    silhouette: 'a-line',
    neckline: 'Bustier',
    embellishment: 'Mirror disc sequin',
    imageUrls: ['https://picsum.photos/seed/2c004a/600/800', 'https://picsum.photos/seed/2c004b/600/800'],
    isFeatured: false, isNew: false, isSale: true, isExclusive: false,
    stockStatus: 'in_stock', slug: 'disco-inferno', createdAt: '2025-10-08T00:00:00Z',
  },
  {
    id: 'jk-008',
    name: 'Violet Storm',
    designer: 'Johnathan Kayne',
    description: 'Dramatic violet duchess satin ball gown with storm-cloud layers of crinkled organza in the skirt. The structured bodice is covered in hand-applied Swarovski crystals that catch light like lightning.',
    price: 2100,
    wholesalePrice: 1050,
    colors: [{ name: 'Violet', hex: '#7F00FF' }, { name: 'Storm Blue', hex: '#4A5568' }],
    sizes: ['0', '2', '4', '6', '8', '10'],
    occasions: ['pageant', 'prom', 'evening'],
    silhouette: 'ballgown',
    neckline: 'Structured strapless',
    embellishment: 'Swarovski crystals',
    imageUrls: ['https://picsum.photos/seed/jk008a/600/800', 'https://picsum.photos/seed/jk008b/600/800'],
    isFeatured: true, isNew: true, isSale: false, isExclusive: true,
    stockStatus: 'low_stock', slug: 'violet-storm', createdAt: '2026-02-20T00:00:00Z',
  },
  {
    id: 'al-008',
    name: 'Blush Reverie',
    designer: 'Ashley Lauren',
    description: 'Romantic blush pink tulle ball gown with a hand-beaded lace bodice and layered skirt. Satin ribbon tie-back adds a youthful, elegant touch. Perfect for prom or a garden party.',
    price: 875,
    wholesalePrice: 437,
    colors: [{ name: 'Blush', hex: '#FFB6C1' }, { name: 'Champagne', hex: '#FAD5A5' }, { name: 'White', hex: '#FFFFFF' }],
    sizes: ['00', '0', '2', '4', '6', '8', '10', '12', '14', '16'],
    occasions: ['prom', 'bridal', 'sweet16'],
    silhouette: 'ballgown',
    neckline: 'Lace sweetheart',
    embellishment: 'Beaded lace',
    imageUrls: ['https://picsum.photos/seed/al008a/600/800', 'https://picsum.photos/seed/al008b/600/800'],
    isFeatured: false, isNew: true, isSale: false, isExclusive: false,
    stockStatus: 'in_stock', slug: 'blush-reverie', createdAt: '2026-01-18T00:00:00Z',
  },
  {
    id: 'ja-007',
    name: 'Power Play',
    designer: 'Jessica Angel',
    description: 'Fierce red power suit with wide-leg trousers and a plunging blazer — the ultimate non-dress prom look. Rhinestone lapel pin and coordinating bodysuit included.',
    price: 695,
    wholesalePrice: 347,
    colors: [{ name: 'Red', hex: '#FF0000' }, { name: 'White', hex: '#FFFFFF' }, { name: 'Black', hex: '#000000' }],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    occasions: ['prom', 'homecoming'],
    silhouette: 'column',
    neckline: 'Blazer plunge',
    embellishment: 'Rhinestone lapel',
    imageUrls: ['https://picsum.photos/seed/ja007a/600/800', 'https://picsum.photos/seed/ja007b/600/800'],
    isFeatured: false, isNew: true, isSale: false, isExclusive: true,
    stockStatus: 'in_stock', slug: 'power-play', createdAt: '2026-02-14T00:00:00Z',
  },
  {
    id: 'td-006',
    name: 'Lilac Lullaby',
    designer: 'Tiffany Designs',
    description: 'A soft and dreamy lilac organza ball gown with butterfly sleeves and a cascading floral skirt. The pastel hue and delicate construction make this the ultimate romantic prom statement.',
    price: 599,
    wholesalePrice: 299,
    colors: [{ name: 'Lilac', hex: '#C8A2C8' }, { name: 'Periwinkle', hex: '#CCCCFF' }, { name: 'Mint', hex: '#98FF98' }],
    sizes: ['00', '0', '2', '4', '6', '8', '10', '12', '14', '16', '18', '20'],
    occasions: ['prom', 'sweet16', 'quinceanera'],
    silhouette: 'ballgown',
    neckline: 'Off-shoulder butterfly',
    embellishment: 'Floral organza',
    imageUrls: ['https://picsum.photos/seed/td006a/600/800', 'https://picsum.photos/seed/td006b/600/800'],
    isFeatured: false, isNew: false, isSale: false, isExclusive: false,
    stockStatus: 'in_stock', slug: 'lilac-lullaby', createdAt: '2025-12-28T00:00:00Z',
  },
  {
    id: 'cl-005',
    name: 'Venice Gold',
    designer: 'Chandalier LA',
    description: 'Luxe gold lamé wrap dress with dramatic wide sleeves and a belted waist. The reflective fabric creates an otherworldly glow effect under any lighting.',
    price: 729,
    wholesalePrice: 364,
    colors: [{ name: 'Gold', hex: '#D4AF72' }, { name: 'Silver', hex: '#C0C0C0' }],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    occasions: ['prom', 'pageant', 'evening'],
    silhouette: 'a-line',
    neckline: 'Wrap',
    embellishment: 'Lamé fabric',
    imageUrls: ['https://picsum.photos/seed/cl005a/600/800', 'https://picsum.photos/seed/cl005b/600/800'],
    isFeatured: false, isNew: false, isSale: false, isExclusive: false,
    stockStatus: 'in_stock', slug: 'venice-gold', createdAt: '2025-11-25T00:00:00Z',
  },
  {
    id: '2c-005',
    name: 'Tropical Dream',
    designer: '2Cute Prom',
    description: 'Vibrant tropical print chiffon maxi with a sweetheart neckline and adjustable straps. The bold floral and leaf print is offset by a clean structured bodice. Bring vacation energy to prom night.',
    price: 319,
    wholesalePrice: 159,
    colors: [{ name: 'Tropical Multi', hex: '#228B22' }],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    occasions: ['prom', 'homecoming', 'sweet16'],
    silhouette: 'a-line',
    neckline: 'Sweetheart',
    embellishment: 'Tropical print',
    imageUrls: ['https://picsum.photos/seed/2c005a/600/800', 'https://picsum.photos/seed/2c005b/600/800'],
    isFeatured: false, isNew: false, isSale: true, isExclusive: false,
    stockStatus: 'in_stock', slug: 'tropical-dream', createdAt: '2025-09-20T00:00:00Z',
  },
  {
    id: 'jk-009',
    name: 'Pearl Empress',
    designer: 'Johnathan Kayne',
    description: 'An opulent pearl-white duchess satin ball gown with a cathedral train and hand-placed freshwater pearl embellishments across the entire bodice and skirt hem. True pageant royalty.',
    price: 2400,
    wholesalePrice: 1200,
    colors: [{ name: 'Pearl White', hex: '#F5F5F0' }, { name: 'Ivory', hex: '#FFFFF0' }],
    sizes: ['0', '2', '4', '6', '8', '10', '12'],
    occasions: ['pageant', 'bridal'],
    silhouette: 'ballgown',
    neckline: 'Bateau',
    embellishment: 'Freshwater pearls',
    imageUrls: ['https://picsum.photos/seed/jk009a/600/800', 'https://picsum.photos/seed/jk009b/600/800'],
    isFeatured: true, isNew: false, isSale: false, isExclusive: true,
    stockStatus: 'backordered', slug: 'pearl-empress', createdAt: '2025-08-01T00:00:00Z',
  },
  {
    id: 'al-009',
    name: 'Sage Wisdom',
    designer: 'Ashley Lauren',
    description: 'Sage green crepe column gown with asymmetric draping at the shoulder and a floor-grazing hem with a hidden slit. Understated luxury for the girl with impeccable taste.',
    price: 960,
    wholesalePrice: 480,
    colors: [{ name: 'Sage', hex: '#9CAF88' }, { name: 'Olive', hex: '#808000' }, { name: 'Dusty Blue', hex: '#7BAFB8' }],
    sizes: ['0', '2', '4', '6', '8', '10', '12', '14'],
    occasions: ['bridal', 'prom', 'evening'],
    silhouette: 'column',
    neckline: 'Asymmetric drape',
    embellishment: 'Draped fabric',
    imageUrls: ['https://picsum.photos/seed/al009a/600/800', 'https://picsum.photos/seed/al009b/600/800'],
    isFeatured: false, isNew: true, isSale: false, isExclusive: false,
    stockStatus: 'in_stock', slug: 'sage-wisdom', createdAt: '2026-02-18T00:00:00Z',
  },
  {
    id: 'ja-008',
    name: 'Champagne Problems',
    designer: 'Jessica Angel',
    description: 'Sparkling champagne illusion gown with an all-over beaded mesh bodice and a nude lining that creates a floating-gem effect. The mermaid skirt flares dramatically at mid-thigh.',
    price: 749,
    wholesalePrice: 374,
    colors: [{ name: 'Champagne', hex: '#FAD5A5' }, { name: 'Rose Gold', hex: '#B76E79' }],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    occasions: ['prom', 'pageant', 'evening'],
    silhouette: 'mermaid',
    neckline: 'Illusion',
    embellishment: 'Beaded mesh',
    imageUrls: ['https://picsum.photos/seed/ja008a/600/800', 'https://picsum.photos/seed/ja008b/600/800'],
    isFeatured: false, isNew: false, isSale: false, isExclusive: false,
    stockStatus: 'in_stock', slug: 'champagne-problems', createdAt: '2025-12-22T00:00:00Z',
  },
  {
    id: 'td-007',
    name: 'Flower Crown',
    designer: 'Tiffany Designs',
    description: 'Blush pink tulle A-line with a floral lace bodice and scattered 3D flowers throughout the layered skirt. Includes a coordinating flower crown headband.',
    price: 649,
    wholesalePrice: 324,
    colors: [{ name: 'Blush Pink', hex: '#FFB6C1' }, { name: 'White', hex: '#FFFFFF' }],
    sizes: ['00', '0', '2', '4', '6', '8', '10', '12', '14', '16', '18'],
    occasions: ['prom', 'sweet16', 'quinceanera', 'bridal'],
    silhouette: 'a-line',
    neckline: 'Illusion lace',
    embellishment: '3D flowers + crown',
    imageUrls: ['https://picsum.photos/seed/td007a/600/800', 'https://picsum.photos/seed/td007b/600/800'],
    isFeatured: false, isNew: true, isSale: false, isExclusive: false,
    stockStatus: 'in_stock', slug: 'flower-crown', createdAt: '2026-02-07T00:00:00Z',
  },
  {
    id: 'cl-006',
    name: 'Riviera Blue',
    designer: 'Chandalier LA',
    description: 'Mediterranean-inspired cobalt blue silk georgette maxi dress with a ruched bodice, thin straps, and a side slit that evokes breezy summers on the French Riviera.',
    price: 519,
    wholesalePrice: 259,
    colors: [{ name: 'Cobalt', hex: '#0047AB' }, { name: 'Mediterranean Blue', hex: '#1560BD' }],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    occasions: ['homecoming', 'prom', 'evening'],
    silhouette: 'column',
    neckline: 'Ruched thin-strap',
    embellishment: 'None',
    imageUrls: ['https://picsum.photos/seed/cl006a/600/800', 'https://picsum.photos/seed/cl006b/600/800'],
    isFeatured: false, isNew: false, isSale: false, isExclusive: false,
    stockStatus: 'in_stock', slug: 'riviera-blue', createdAt: '2025-11-30T00:00:00Z',
  },
  {
    id: 'jk-010',
    name: 'Rose Gold Royalty',
    designer: 'Johnathan Kayne',
    description: 'Breathtaking rose gold sequin ball gown with a structured sweetheart bodice and a cascading skirt featuring crystal-embellished layers. The ultimate prom queen statement.',
    price: 1760,
    wholesalePrice: 880,
    colors: [{ name: 'Rose Gold', hex: '#B76E79' }, { name: 'Champagne', hex: '#FAD5A5' }],
    sizes: ['0', '2', '4', '6', '8', '10', '12'],
    occasions: ['prom', 'pageant'],
    silhouette: 'ballgown',
    neckline: 'Structured sweetheart',
    embellishment: 'Sequin with crystals',
    imageUrls: ['https://picsum.photos/seed/jk010a/600/800', 'https://picsum.photos/seed/jk010b/600/800'],
    isFeatured: true, isNew: true, isSale: false, isExclusive: false,
    stockStatus: 'in_stock', slug: 'rose-gold-royalty', createdAt: '2026-01-10T00:00:00Z',
  },
  {
    id: 'al-010',
    name: 'Berry Couture',
    designer: 'Ashley Lauren',
    description: 'Rich berry duchess satin trumpet gown with a structured bodice, dramatic sleeves, and a sweeping train. The jewel-toned berry shade photographs magnificently.',
    price: 1120,
    wholesalePrice: 560,
    colors: [{ name: 'Berry', hex: '#8B0057' }, { name: 'Deep Plum', hex: '#722F37' }],
    sizes: ['0', '2', '4', '6', '8', '10', '12', '14'],
    occasions: ['prom', 'pageant', 'evening'],
    silhouette: 'trumpet',
    neckline: 'Off-shoulder',
    embellishment: 'Dramatic sleeves',
    imageUrls: ['https://picsum.photos/seed/al010a/600/800', 'https://picsum.photos/seed/al010b/600/800'],
    isFeatured: false, isNew: false, isSale: false, isExclusive: true,
    stockStatus: 'in_stock', slug: 'berry-couture', createdAt: '2025-10-25T00:00:00Z',
  },
  {
    id: 'ja-009',
    name: 'Silver Siren',
    designer: 'Jessica Angel',
    description: 'Head-to-toe silver metallic mermaid dress with a crossover neckline and open back. The fabric moves like liquid mercury, creating a hypnotic effect with every movement.',
    price: 649,
    wholesalePrice: 324,
    colors: [{ name: 'Silver', hex: '#C0C0C0' }, { name: 'Gunmetal', hex: '#2C3E50' }],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    occasions: ['prom', 'pageant', 'evening'],
    silhouette: 'mermaid',
    neckline: 'Crossover',
    embellishment: 'Metallic',
    imageUrls: ['https://picsum.photos/seed/ja009a/600/800', 'https://picsum.photos/seed/ja009b/600/800'],
    isFeatured: false, isNew: true, isSale: false, isExclusive: false,
    stockStatus: 'in_stock', slug: 'silver-siren', createdAt: '2026-01-16T00:00:00Z',
  },
  {
    id: 'td-008',
    name: 'Mauve Magic',
    designer: 'Tiffany Designs',
    description: 'Soft mauve tulle ball gown with a beaded lace bodice and layered skirt in gradient shades from dusty rose to deep mauve. The romantic color story makes this a timeless choice.',
    price: 729,
    wholesalePrice: 364,
    colors: [{ name: 'Mauve', hex: '#E0B0B0' }, { name: 'Dusty Rose', hex: '#DCAE96' }, { name: 'Antique Rose', hex: '#A06E6E' }],
    sizes: ['00', '0', '2', '4', '6', '8', '10', '12', '14', '16'],
    occasions: ['prom', 'sweet16', 'bridal'],
    silhouette: 'ballgown',
    neckline: 'Lace sweetheart',
    embellishment: 'Gradient tulle, beaded lace',
    imageUrls: ['https://picsum.photos/seed/td008a/600/800', 'https://picsum.photos/seed/td008b/600/800'],
    isFeatured: false, isNew: false, isSale: false, isExclusive: false,
    stockStatus: 'in_stock', slug: 'mauve-magic', createdAt: '2025-12-18T00:00:00Z',
  },
  {
    id: 'jk-011',
    name: 'Navy Duchess',
    designer: 'Johnathan Kayne',
    description: 'Commanding navy duchess satin ball gown with a full skirt featuring hidden pockets (yes, pockets!) and a hand-beaded bodice with 3D crystal flowers.',
    price: 1490,
    wholesalePrice: 745,
    colors: [{ name: 'Navy', hex: '#000080' }, { name: 'Royal Blue', hex: '#4169E1' }],
    sizes: ['0', '2', '4', '6', '8', '10', '12', '14', '16'],
    occasions: ['prom', 'pageant'],
    silhouette: 'ballgown',
    neckline: 'Strapless',
    embellishment: '3D crystal flowers',
    imageUrls: ['https://picsum.photos/seed/jk011a/600/800', 'https://picsum.photos/seed/jk011b/600/800'],
    isFeatured: false, isNew: false, isSale: false, isExclusive: false,
    stockStatus: 'in_stock', slug: 'navy-duchess', createdAt: '2025-12-01T00:00:00Z',
  },
  {
    id: 'al-011',
    name: 'Gilded Lily',
    designer: 'Ashley Lauren',
    description: 'Gold sequin column gown with lily-inspired 3D fabric flowers cascading down the bodice. The fitted silhouette ends in a subtle flare at the knee for elegant movement.',
    price: 1080,
    wholesalePrice: 540,
    colors: [{ name: 'Gold', hex: '#D4AF72' }, { name: 'Champagne', hex: '#FAD5A5' }],
    sizes: ['0', '2', '4', '6', '8', '10', '12'],
    occasions: ['prom', 'pageant', 'evening'],
    silhouette: 'sheath',
    neckline: 'V-neck',
    embellishment: '3D lily flowers',
    imageUrls: ['https://picsum.photos/seed/al011a/600/800', 'https://picsum.photos/seed/al011b/600/800'],
    isFeatured: false, isNew: false, isSale: true, isExclusive: false,
    stockStatus: 'low_stock', slug: 'gilded-lily', createdAt: '2025-09-10T00:00:00Z',
  },
  {
    id: 'ja-010',
    name: 'Jade Envy',
    designer: 'Jessica Angel',
    description: 'Rich jade green jersey siren gown with a plunging V-neck, crossover straps at the back, and a ruched waist that creates a naturally sculpted look.',
    price: 489,
    wholesalePrice: 244,
    colors: [{ name: 'Jade', hex: '#00A36C' }, { name: 'Emerald', hex: '#50C878' }, { name: 'Hunter', hex: '#355E3B' }],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    occasions: ['prom', 'homecoming', 'evening'],
    silhouette: 'column',
    neckline: 'Plunge V',
    embellishment: 'Ruching',
    imageUrls: ['https://picsum.photos/seed/ja010a/600/800', 'https://picsum.photos/seed/ja010b/600/800'],
    isFeatured: false, isNew: true, isSale: false, isExclusive: false,
    stockStatus: 'in_stock', slug: 'jade-envy', createdAt: '2026-02-22T00:00:00Z',
  },
  {
    id: 'td-009',
    name: 'Starlight Express',
    designer: 'Tiffany Designs',
    description: 'Silver glitter tulle ball gown with a strapless sequin bodice and full skirt with hidden LED-effect glitter threads. Under a black light, this dress literally glows.',
    price: 819,
    wholesalePrice: 409,
    colors: [{ name: 'Silver', hex: '#C0C0C0' }, { name: 'White', hex: '#FFFFFF' }],
    sizes: ['0', '2', '4', '6', '8', '10', '12', '14', '16'],
    occasions: ['prom', 'sweet16'],
    silhouette: 'ballgown',
    neckline: 'Strapless sequin',
    embellishment: 'Glitter LED-effect tulle',
    imageUrls: ['https://picsum.photos/seed/td009a/600/800', 'https://picsum.photos/seed/td009b/600/800'],
    isFeatured: false, isNew: true, isSale: false, isExclusive: true,
    stockStatus: 'in_stock', slug: 'starlight-express', createdAt: '2026-01-28T00:00:00Z',
  },
  {
    id: 'jk-012',
    name: 'Obsidian Phoenix',
    designer: 'Johnathan Kayne',
    description: 'The most dramatic dress in the collection. Black duchess satin ball gown with a feathered hem that graduates from black to iridescent flame colors. For the girl who is already a legend.',
    price: 2200,
    wholesalePrice: 1100,
    colors: [{ name: 'Obsidian', hex: '#0B0C10' }],
    sizes: ['0', '2', '4', '6', '8', '10'],
    occasions: ['pageant', 'prom', 'evening'],
    silhouette: 'ballgown',
    neckline: 'Structured off-shoulder',
    embellishment: 'Iridescent feathers',
    imageUrls: ['https://picsum.photos/seed/jk012a/600/800', 'https://picsum.photos/seed/jk012b/600/800'],
    isFeatured: true, isNew: false, isSale: false, isExclusive: true,
    stockStatus: 'low_stock', slug: 'obsidian-phoenix', createdAt: '2025-07-01T00:00:00Z',
  },
]

// ── MARKETING ASSETS ─────────────────────────────────────────

export const marketingAssets: MarketingAsset[] = [
  {
    id: 'ma-001',
    title: '2026 Prom Lookbook',
    description: 'Full catalog of our Spring 2026 prom collection — 64 pages of editorial photography, style guides, and collection highlights.',
    category: 'lookbook',
    thumbnailUrl: 'https://picsum.photos/seed/lb001/400/300',
    fileSize: '24 MB',
    fileType: 'PDF',
    downloadUrl: '/assets/2026-prom-lookbook.pdf',
    year: 2026,
  },
  {
    id: 'ma-002',
    title: 'Bridal Collection Lookbook',
    description: 'Bridal and formal occasion lookbook featuring all designers, styling tips, and wedding party coordination guides.',
    category: 'lookbook',
    thumbnailUrl: 'https://picsum.photos/seed/lb002/400/300',
    fileSize: '18 MB',
    fileType: 'PDF',
    downloadUrl: '/assets/bridal-lookbook.pdf',
    year: 2026,
  },
  {
    id: 'ma-003',
    title: 'Designer Spotlight Social Kit',
    description: 'Curated Instagram & TikTok content package — 30 posts, 15 Stories templates, and 5 Reels concepts per designer.',
    category: 'social',
    thumbnailUrl: 'https://picsum.photos/seed/lb003/400/300',
    fileSize: '156 MB',
    fileType: 'ZIP',
    downloadUrl: '/assets/social-kit.zip',
    year: 2026,
  },
  {
    id: 'ma-004',
    title: 'In-Store Signage Templates',
    description: 'Print-ready signage templates including window displays, fitting room cards, and promotional banners in multiple sizes.',
    category: 'signage',
    thumbnailUrl: 'https://picsum.photos/seed/lb004/400/300',
    fileSize: '85 MB',
    fileType: 'ZIP',
    downloadUrl: '/assets/signage-templates.zip',
    year: 2026,
  },
  {
    id: 'ma-005',
    title: 'Email Campaign Templates',
    description: 'Ready-to-use email marketing templates for prom season, new arrivals, and promotional events — compatible with all major email platforms.',
    category: 'email',
    thumbnailUrl: 'https://picsum.photos/seed/lb005/400/300',
    fileSize: '12 MB',
    fileType: 'ZIP',
    downloadUrl: '/assets/email-templates.zip',
    year: 2026,
  },
]

// ── SAMPLE VENDOR ANALYTICS ───────────────────────────────────

export const sampleVendorAnalytics: VendorAnalytics = {
  totalOrdersMTD: 47,
  totalOrdersMTDTrend: 12.5,
  revenueMTD: 38420,
  revenueMTDTrend: 8.2,
  topSellingStyle: dresses[0],
  avgOrderValue: 817,
  avgOrderValueTrend: -2.1,
  revenueByMonth: [
    { month: 'Mar', revenue: 28500 },
    { month: 'Apr', revenue: 42000 },
    { month: 'May', revenue: 65000 },
    { month: 'Jun', revenue: 38000 },
    { month: 'Jul', revenue: 22000 },
    { month: 'Aug', revenue: 31000 },
    { month: 'Sep', revenue: 45000 },
    { month: 'Oct', revenue: 52000 },
    { month: 'Nov', revenue: 41000 },
    { month: 'Dec', revenue: 29000 },
    { month: 'Jan', revenue: 35000 },
    { month: 'Feb', revenue: 38420 },
  ],
  ordersByOccasion: [
    { occasion: 'Prom', orders: 24, color: '#D4AF72' },
    { occasion: 'Bridal', orders: 11, color: '#F2B5C7' },
    { occasion: 'Evening', orders: 7, color: '#9B6FD4' },
    { occasion: 'Pageant', orders: 5, color: '#F8F4F0' },
  ],
}

// ── HELPERS ───────────────────────────────────────────────────

export function getDressBySlug(slug: string): Dress | undefined {
  return dresses.find((d) => d.slug === slug)
}

export function getDressesByDesigner(designer: string): Dress[] {
  return dresses.filter((d) => d.designer === designer)
}

export function getDressesByOccasion(occasion: string): Dress[] {
  return dresses.filter((d) => d.occasions.includes(occasion as any))
}

export function getFeaturedDresses(): Dress[] {
  return dresses.filter((d) => d.isFeatured)
}

export function getNewDresses(): Dress[] {
  return dresses.filter((d) => d.isNew)
}

export function getSaleDresses(): Dress[] {
  return dresses.filter((d) => d.isSale)
}

export function getStoreById(id: number): Store | undefined {
  return stores.find((s) => s.id === id)
}

export function getHQStore(): Store {
  return stores.find((s) => s.isHQ)!
}

export function getDesignerBySlug(slug: string): DesignerProfile | undefined {
  return designers.find((d) => d.slug === slug)
}

// Uppercase aliases for components that import STORES, DRESSES, DESIGNERS
export const STORES = stores
export const DRESSES = dresses
export const DESIGNERS = designers
